services:
  lobe-chat:
    image: lobehub/lobe-chat-database:1.143.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3210"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_PROXY_URL=${OPENAI_PROXY_URL}
      - ACCESS_CODE=${ACCESS_CODE}
      - OPENAI_MODEL_LIST=${OPENAI_MODEL_LIST}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEFAULT_AGENT_CONFIG=${DEFAULT_AGENT_CONFIG}
      - SYSTEM_AGENT=${SYSTEM_AGENT}
      - APP_URL=${APP_URL}
      - KEY_VAULTS_SECRET=${KEY_VAULTS_SECRET}
      - DATABASE_URL=postgres://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}
      - NEXT_AUTH_SSO_PROVIDERS=${NEXT_AUTH_SSO_PROVIDERS}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_AUTH_SECRET=${NEXT_AUTH_SECRET}
      - AUTH_LOGTO_ID=${AUTH_LOGTO_ID}
      - AUTH_LOGTO_SECRET=${AUTH_LOGTO_SECRET}
      - AUTH_LOGTO_ISSUER=${AUTH_LOGTO_ISSUER}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_PUBLIC_DOMAIN=${S3_PUBLIC_DOMAIN}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    labels:
      createdBy: "Apps"
networks:
  1panel-network:  
    external: true
